# these are the different stages for our pipelines
# jobs in the same stage run in parallel 
# next stage doesn't start until previous stage finishes OK
# by now we only do build and test, we could add another stage "deploy" if needed
stages:
  - build
  - test

# this is executed before doing anything else
before_script:
  - echo "hi, I am the before script"
  - echo "Trying to list the contents of /export/soft"
  - yum -y install tcl
  - ls /export/soft
  - mkdir -p /scicore/soft/{apps,modules}

# BUILD STAGE
build:centos6.6:
  stage: build
  image: centos:6.6
  script:
  - echo "Hi from the centos 6.6 container. I am in the build stage"
  - cat /etc/redhat-release
  - ln -s /export/soft/apps/centos6/generic /scicore/soft/apps
  - ln -s /export/soft/modules/centos6/generic/all /scicore/soft/modules
  - source /export/soft/lua_lmod/centos6/lmod/lmod/init/bash
  - module use /scicore/soft/modules/all
  - module load Boost/1.53.0-goolf-1.4.10-Python-2.7.5
  - module list

build:centos7.3:
  stage: build
  image: centos:7.3.1611
  script:
  - echo "Hi from the centos 7.3 container. I am in the build stage"
  - cat /etc/redhat-release
  - echo "Trying to list the contents of /export/soft"
  - ls /export/soft

# TESTS STAGE
test:centos6.6:
  stage: test
  image: centos:6.6
  script:
  - echo "Hi from the centos 6.6 container. Here I run unit tests if build finished ok"
  - cat /etc/redhat-release
  - source /export/soft/lua_lmod/centos6/lmod/lmod/init/bash
  - module list

test:centos7.3:
  stage: test
  image: centos:7.3.1611
  script:
  - echo "Hi from the centos 7.3 container. Here I run unit tests if build finished ok"
