# these are the different stages for our pipelines
# jobs in the same stage run in parallel 
# next stage doesn't start until previous stage finishes with 'OK'
# by now we only do build and test, we could add another stage "deploy" if
# needed
stages:
  - build
  - test

# this is executed before doing anything else
before_script:
  - echo "Running global 'before_script'..."
  - yum -y -q -e 0 install tcl
  - mkdir -p /scicore/soft/{apps,modules}
  - ln -s /export/soft/apps/centos6/generic /scicore/soft/apps
  - ln -s /export/soft/modules/centos6/generic/all /scicore/soft/modules
  - source /export/soft/lua_lmod/centos6/lmod/lmod/init/bash
  - module use /scicore/soft/modules/all
  - echo "... done running global 'before_script'."

# BUILD STAGE
build:centos6.6:
  stage: build
  image: centos:6.6
  script:
  - echo "Building on CentOS 6..."
  - cat /etc/redhat-release
  - echo "... done building on CentOS 6."

# TESTS STAGE
test:centos6.6:
  stage: test
  image: centos:6.6
  script:
  - echo "Testing on CentOS 6..."
  - cat /etc/redhat-release
  - echo "... done testing on CentOS 6."
